// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Jun 28 16:49:54 2016

adapt adapt_inst
(
	.GPIO_1(GPIO_1_sig) ,	// input [1]:PIO_1[1]] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [3]:PIO_1[3]] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [4]:PIO_1[4]] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [5]:PIO_1[5]] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [6]:PIO_1[6]] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [16:7] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [26:17] GPIO_1_sig
	.GPIO_1(GPIO_1_sig) ,	// input [35:27] GPIO_1_sig
	.VGA_G(VGA_G_sig) ,	// output [9:0] VGA_G_sig
	.VGA_R(VGA_R_sig) ,	// output [9:0] VGA_R_sig
	.VGA_SYNC(VGA_SYNC_sig) ,	// output  VGA_SYNC_sig
	.VGA_BLANK(VGA_BLANK_sig) ,	// output  VGA_BLANK_sig
	.VGA_VS(VGA_VS_sig) ,	// output  VGA_VS_sig
	.VGA_HS(VGA_HS_sig) ,	// output  VGA_HS_sig
	.VGA_CLK(VGA_CLK_sig) ,	// output  VGA_CLK_sig
	.VGA_B(VGA_B_sig) 	// output [8:0] VGA_B_sig
);

