# TCL File Generated by Component Editor 10.0
# Wed Aug 11 11:39:56 CST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | CAMERA_IF "CAMERA_IF" v1.0
# | null 2010.08.11.11:39:56
# | 
# | 
# | E:/D5M/cd/Demonstration/DE2_70_CAMERA/HW/DE2_70_CAMERA/ip/TERASIC_CAMERA/CAMERA_IF.v
# | 
# |    ./CAMERA_IF.v syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module CAMERA_IF
# | 
set_module_property DESCRIPTION ""
set_module_property NAME CAMERA_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Terasic Technologies Inc."
set_module_property DISPLAY_NAME CAMERA_IF
set_module_property TOP_LEVEL_HDL_FILE CAMERA_IF.v
set_module_property TOP_LEVEL_HDL_MODULE CAMERA_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file CAMERA_IF.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clock
# | 
add_interface s1_clock clock end

set_interface_property s1_clock ENABLED true

add_interface_port s1_clock avs_s1_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clock_reset
# | 
add_interface s1_clock_reset reset end
set_interface_property s1_clock_reset associatedClock s1_clock
set_interface_property s1_clock_reset synchronousEdges DEASSERT

set_interface_property s1_clock_reset ASSOCIATED_CLOCK s1_clock
set_interface_property s1_clock_reset ENABLED true

add_interface_port s1_clock_reset avs_s1_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 associatedClock s1_clock
set_interface_property s1 associatedReset s1_clock_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ASSOCIATED_CLOCK s1_clock
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_export
# | 
add_interface s1_export conduit end

set_interface_property s1_export ENABLED true

add_interface_port s1_export avs_s1_export_clk export Output 1
add_interface_port s1_export avs_s1_export_address export Output 2
add_interface_port s1_export avs_s1_export_readdata export Input 32
add_interface_port s1_export avs_s1_export_read export Output 1
add_interface_port s1_export avs_s1_export_writedata export Output 32
add_interface_port s1_export avs_s1_export_write export Output 1
add_interface_port s1_export avs_s1_export_reset export Output 1
# | 
# +-----------------------------------
